# Generated by Django 2.2 on 2023-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorNo', models.IntegerField()),
                ('plotNo', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
